version: '3'

services:
  mlflow:
    build: mlflow
    container_name: mlflow
    env_file:
      - .env
    depends_on:
      - postgres
      - minio
    ports:
      - 5000:5000

  minio:
    image: minio/minio
    container_name: mlflow_minio
    command: server --address ":9000" --console-address ":9001" /data
    env_file:
      - .env
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres:
    image: postgres
    container_name: mlflow_postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  mc:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      /tmp/wait-for-it.sh minio:9000 &&
      /usr/bin/mc alias set minio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} &&
      /usr/bin/mc mb minio/mlflow;
      /usr/bin/mc anonymous set public minio/mlflow;
      exit 0;
      "
    volumes:
      - ./wait-for-it.sh:/tmp/wait-for-it.sh
